language: node_js

node_js:
    - "16.8"

install:
    - npm install

branches:
    only:
        - main

script:
    - npm run build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    target-branch: gh-pages
    local-dir: dist
    on:
        branch: main
